name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&rank_icon=github&show=reviews,discussions_started,discussions_answered,prs_merged,prs_merged_percentage,prs_commented,prs_reviewed,issues_commented&show_icons=true&include_all_commits=true&locale=en&bg_color=0,A9E43A,01C45B&theme=graywhite&hide_border=true
          
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate top langs card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&langs_count=10&layout=pie&bg_color=0,A9E43A,01C45B&theme=graywhite&hide_border=true

          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
